Repository rust-random/rand, pull requests merged in 2018-03, with the labels that each got.

#288 Add rand-core sub-crate and update version numbers
  .travis.yml
  Cargo.toml
  appveyor.yml
  rand-core/Cargo.toml
  rand-core/LICENSE-APACHE
  rand-core/LICENSE-MIT
  rand-core/README.md
  rand-core/src/error.rs
  rand-core/src/impls.rs
  rand-core/src/le.rs
  rand-core/src/lib.rs
  src/entropy_rng.rs
  src/jitter.rs
  src/lib.rs
  src/mock.rs
  src/os.rs
  src/prng/chacha.rs
  src/prng/hc128.rs
  src/prng/isaac.rs
  src/prng/isaac64.rs
  src/prng/xorshift.rs
  src/read.rs
  utils/ci/script.sh
Labels: P-high

#302 Make NewRng::new() return Self without Result wrapper
  benches/distributions.rs
  benches/generators.rs
  src/distributions/exponential.rs
  src/distributions/float.rs
  src/distributions/mod.rs
  src/distributions/normal.rs
  src/lib.rs
Labels: E-question, X-enhancement

#304 Improve doc for NewRng::new alternative
  src/lib.rs
Labels: C-docs, E-review

#303 Blockrng: template over element type
  benches/generators.rs
  rand-core/src/impls.rs
  rand-core/src/lib.rs
  src/lib.rs
  src/prng/chacha.rs
  src/prng/hc128.rs
  src/prng/mod.rs
  src/reseeding.rs
  src/thread_rng.rs
Labels: B-API, E-review, P-high, T-RNG, X-enhancement

#285 Use UnsafeCell in ThreadRng
  src/thread_rng.rs
Labels: C-optimisation, E-review, P-low

#96 Add binomial and Poisson distributions
  src/distributions/binomial.rs
  src/distributions/log_gamma.rs
  src/distributions/mod.rs
  src/distributions/poisson.rs
Labels: E-review, F-new-int, P-medium

#312 Add trait implementation guidance
  rand-core/src/lib.rs
  src/thread_rng.rs
Labels: C-docs, E-review, P-high

#317 homepage, bench improvement and doc fix
  Cargo.toml
  benches/distributions.rs
  benches/generators.rs
  rand-core/Cargo.toml
  rand-core/README.md
Labels: E-review, P-high

#308 Deprecate Rng::gen_weighted_bool
  benches/generators.rs
  benches/misc.rs
  src/distributions/binomial.rs
  src/lib.rs
Labels: B-API, E-review, F-new-int, P-high, T-distributions, X-enhancement

#324 Add update guide
  CHANGELOG.md
  UPDATING.md
Labels: C-docs

#326 Update documentation for ReadRng error handling
  src/read.rs
Labels: C-docs

#319 Generics
  benches/misc.rs
  rand-core/src/impls.rs
  rand-core/src/lib.rs
  src/distributions/other.rs
  src/lib.rs
  src/prng/chacha.rs
  src/prng/hc128.rs
  src/prng/isaac.rs
  src/prng/isaac64.rs
  src/prng/xorshift.rs
  src/seq.rs
Labels: B-API, E-review, P-high, X-enhancement

#330 Changes to rand_core readme
  Cargo.toml
  README.md
  rand_core/Cargo.toml
  rand_core/README.md
Labels: C-docs

#336 Put stdweb dependency behind a target feature
  .travis.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  src/lib.rs
  src/os.rs
  src/thread_rng.rs
Labels: E-help-wanted, P-medium, X-experimental

#333 Osrng doc
  CHANGELOG.md
  UPDATING.md
  src/os.rs
Labels: C-docs
