Repository rust-random/rand, pull requests merged in 2018-06, with the labels that each got.

#491 Add API for getting a bool with chance of exactly 1-in-10 or 2-in-3
  benches/misc.rs
  src/distributions/bernoulli.rs
  src/lib.rs
Labels: F-new-int, T-distributions

#485 Support for Dirichlet distribution
  src/distributions/dirichlet.rs
  src/distributions/mod.rs
Labels: D-changes, P-medium, T-distributions

#506 Make Uniform and its helper traits use arguments of type Borrow<X>
  src/distributions/uniform.rs
  src/lib.rs
Labels: D-review

#483 Sequence functionality: API revisions
  benches/misc.rs
  benches/seq.rs
  examples/monty-hall.rs
  src/lib.rs
  src/prelude.rs
  src/rngs/thread.rs
  src/seq.rs
Labels: B-API, E-question, F-new-int, T-sequences, X-discussion

#466 Add Unix fork protection
  src/lib.rs
  src/rngs/adapter/reseeding.rs
  src/rngs/mod.rs
Labels: T-entropy
