Repository rust-random/rand, pull requests merged in 2018-05, with the labels that each got.

#425 BlockRng: make core public and remove inner() and inner_mut()
  rand_core/CHANGELOG.md
  rand_core/src/impls.rs
  src/prng/chacha.rs
  src/reseeding.rs
Labels: B-API, E-question, P-high

#433 Distributions documentation
  src/distributions/mod.rs
  src/distributions/uniform.rs
  src/lib.rs
Labels: C-docs

#411 Implement Bernoulli distribution
  benches/misc.rs
  src/distributions/bernoulli.rs
  src/distributions/binomial.rs
  src/distributions/mod.rs
  src/lib.rs
  tests/bool.rs
Labels: B-value, P-high

#423 Documentation
  rand_core/src/impls.rs
  rand_core/src/lib.rs
  src/distributions/binomial.rs
  src/distributions/exponential.rs
  src/distributions/float.rs
  src/distributions/gamma.rs
  src/distributions/mod.rs
  src/distributions/normal.rs
  src/distributions/other.rs
  src/distributions/poisson.rs
  src/lib.rs
  src/prng/chacha.rs
  src/prng/hc128.rs
  src/prng/isaac.rs
  src/prng/mod.rs
  src/rngs/adapter/read.rs
  src/rngs/entropy.rs
  src/rngs/jitter.rs
  src/rngs/mock.rs
  src/rngs/os.rs
  src/seq.rs
Labels: C-docs
