Repository rust-random/rand, pull requests merged in 2018-07, with the labels that each got.

#477 Make Uniform<f32/f64> and gen_range<f32/f64> honor limits strictly. Resolves #476
  benches/distributions.rs
  src/distributions/float.rs
  src/distributions/uniform.rs
  src/distributions/utils.rs
Labels: D-changes, D-review

#551 Move ISAAC generators to their own crate
  Cargo.toml
  benches/generators.rs
  rand_isaac/CHANGELOG.md
  rand_isaac/Cargo.toml
  rand_isaac/LICENSE-APACHE
  rand_isaac/LICENSE-MIT
  rand_isaac/README.md
  rand_isaac/src/isaac.rs
  rand_isaac/src/isaac64.rs
  rand_isaac/src/isaac_array.rs
  rand_isaac/src/lib.rs
  src/deprecated.rs
  src/lib.rs
  src/prng/mod.rs
Labels: D-review

#544 Doc and policies
  README.md
  doc/README.md
Labels: C-docs, D-review, E-question

#542 fix SIMD integer endian
  src/distributions/integer.rs
Labels: P-postpone

#563 Extend CI configuration
  .travis.yml
  appveyor.yml
  utils/ci/script.sh
Labels: D-changes

#479 seq: use Floyd's combination algorithm to sample indices
  CHANGELOG.md
  benches/seq.rs
  src/lib.rs
  src/seq/index.rs
  src/seq/mod.rs
Labels: B-API, D-review, T-sequences

#571 Replace `i128_support` feature with compile-time detection
  CHANGELOG.md
  Cargo.toml
  README.md
  build.rs
  src/deprecated.rs
  src/distributions/integer.rs
  src/distributions/uniform.rs
  src/distributions/utils.rs
  src/lib.rs
  src/prng/chacha.rs
Labels: E-question
